# SwiftLint Rules: https://github.com/realm/SwiftLint/blob/master/Rules.md

excluded: # paths to ignore during linting. Takes precedence over `included`.
- Pods
- PassToTests/Main/GeneratedMocks.swift
disabled_rules:
- line_length
- type_name
- redundant_string_enum_value
- shorthand_operator
- identifier_name
- function_body_length
- closure_body_length
- multiple_closures_with_trailing_closure
- superfluous_disable_command
- notification_center_detachment
opt_in_rules:
- anyobject_protocol
- array_init
- attributes
- closure_body_length
- closure_end_indentation
- closure_spacing
- collection_alignment
- contains_over_first_not_nil

- discouraged_optional_boolean
- empty_string
- empty_xctest_method
- explicit_init
- explicit_self
- extension_access_modifier
- fallthrough
- fatal_error_message
- file_name
- first_where
- force_unwrapping
- identical_operands
- implicit_return
- implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_random
- literal_expression_end_indentation
- lower_acl_than_parent
- missing_docs
- modifier_order
- multiline_arguments
- multiline_literal_brackets
- multiline_parameters
- nimble_operator
- no_extension_access_modifier
- number_separator
- operator_usage_whitespace
- overridden_super_call
- override_in_extension
- pattern_matching_keywords
- prefixed_toplevel_constant
- prohibited_super_call
- quick_discouraged_call
- quick_discouraged_focused_test
- quick_discouraged_pending_test
- redundant_nil_coalescing
- redundant_type_annotation
- required_enum_case
- single_test_class
- sorted_first_last
- sorted_imports
- static_operator
- strict_fileprivate
- switch_case_on_newline
- toggle_bool
- unavailable_function
- unneeded_parentheses_in_closure_argument
- untyped_error_in_catch
- unused_import
- unused_private_declaration
- vertical_parameter_alignment_on_call
- vertical_whitespace_between_cases
- vertical_whitespace_closing_braces
- vertical_whitespace_opening_braces
- xct_specific_matcher
- yoda_condition

type_body_length:
- 800 #warning
- 1200 #error

file_length:
- 1000 #warning
- 1200 #error

large_tuple:
- 4 #warning
- 6 #error

function_parameter_count:
- 8 #warning
- 10 #error

